name: front
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_svg: ^1.1.6
  animated_text_kit: ^4.2.2
  url_launcher: ^6.1.7
  flutter_web_auth: ^0.5.0
  http: ^0.13.5
  shared_preferences: ^2.0.15
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  provider: ^6.0.5
  flutter_riverpod: ^1.0.3
  dio: ^4.0.6
  dropdown_button2: ^1.9.2
  pie_chart: ^5.3.2
  flutter_dotenv: ^5.0.2
  hooks_riverpod: ^1.0.4
  confetti: ^0.7.0
  google_fonts: ^3.0.1
  flutter_markdown: ^0.6.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.3.2
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
